Tuodaan kirjasto

In [21]:
import numpy as np

#2.1 – Tasaväliset arvot väliltä 0–1
Tässä tehtävässä tehdään taulukko, jossa on 20 lukua. Ne ovat tasaisesti jakautuneet nollan ja ykkösen välille.

In [22]:
start = 0
stop = 1
count = 20
spacing_array = np.linspace(start, stop, num=count)

print("teht 2.1  Tasaväliset arvot (0-1):")
print(spacing_array)


teht 2.1  Tasaväliset arvot (0-1):
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


#2.2 – Kokonaisluvut 0–99 matriisimuodossa

Tässä tehtävässä tehdään numerot 0–99. Ne laitetaan matriisiin eli taulukkoon, jossa on 5 riviä ja 20 saraketta.

In [25]:
numbers = np.arange(100)
reshaped_matrix = numbers.reshape((5, -1)) 

print("teht 2.2 - 5x20 matriisi:")
print(reshaped_matrix)


teht 2.2 - 5x20 matriisi:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


#Tehtävä 2.3 – Satunnaiset luvut ja keskiarvo

Tässä tehtävässä tehdään 15 satunnaista lukua. Niistä lasketaan keskiarvo ja kuinka paljon luvut vaihtelevat.

In [31]:
rand_data = np.random.random_sample(15)
mean_val = np.round(rand_data.mean(), 3)
std_val = np.round(rand_data.std(), 3)

print("teht 2.3  Satunnaiset arvot:")
print("Data:", rand_data)
print("Keskiarvo:", mean_val)
print("Keskihajonta:", std_val)


teht 2.3  Satunnaiset arvot:
Data: [0.92800576 0.60396101 0.78472495 0.90475827 0.27723963 0.15469907
 0.15219448 0.17564677 0.66254783 0.22997118 0.32284356 0.0545272
 0.36608099 0.86197161 0.45015633]
Keskiarvo: 0.462
Keskihajonta: 0.294
