Tuodaan kirjasto

In [10]:
import numpy as np
import seaborn as sns

#2.1 – Tasaväliset arvot väliltä 0–1
Tässä tehtävässä tehdään taulukko, jossa on 20 lukua. Ne ovat tasaisesti jakautuneet nollan ja ykkösen välille.

In [11]:
start = 0
stop = 1
count = 20
spacing_array = np.linspace(start, stop, num=count)

print("teht 2.1  Tasaväliset arvot (0-1):")
print(spacing_array)


teht 2.1  Tasaväliset arvot (0-1):
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


#2.2 – Kokonaisluvut 0–99 matriisimuodossa

Tässä tehtävässä tehdään numerot 0–99. Ne laitetaan matriisiin eli taulukkoon, jossa on 5 riviä ja 20 saraketta.

In [12]:
numbers = np.arange(100)
reshaped_matrix = numbers.reshape((5, -1)) 

print("teht 2.2 - 5x20 matriisi:")
print(reshaped_matrix)


teht 2.2 - 5x20 matriisi:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


#Tehtävä 2.3 – Satunnaiset luvut ja keskiarvo

Tässä tehtävässä tehdään 15 satunnaista lukua. Niistä lasketaan keskiarvo ja kuinka paljon luvut vaihtelevat.

In [13]:
rand_data = np.random.random_sample(15)
mean_val = np.round(rand_data.mean(), 3)
std_val = np.round(rand_data.std(), 3)

print("teht 2.3  Satunnaiset arvot:")
print("Data:", rand_data)
print("Keskiarvo:", mean_val)
print("Keskihajonta:", std_val)


teht 2.3  Satunnaiset arvot:
Data: [0.77538308 0.64874939 0.44809515 0.92008886 0.58694308 0.45288618
 0.59890795 0.5774576  0.39663285 0.21867003 0.24559293 0.5019538
 0.17068974 0.25628512 0.89475674]
Keskiarvo: 0.513
Keskihajonta: 0.228


Ladataan Titanic data

In [14]:
titanic = sns.load_dataset("titanic")

# Ryhmitellään sukupuolen ja luokan mukaan sekä lasketaanh selviydyineiden osuus

In [15]:
selviytymiset = titanic.groupby(["sex", "pclass"])["survived"].mean().reset_index()

# Muunnetaan prosentti muotoon

In [16]:
selviytymiset["survival_rate_percent"] = (selviytymiset["survived"] * 100).round(1)


# Tulostetaan 

In [17]:
print("Selviytymisprosentit sukupuolen ja luokan mukaan:\n")
print(selviytymiset)

Selviytymisprosentit sukupuolen ja luokan mukaan:

      sex  pclass  survived  survival_rate_percent
0  female       1  0.968085                   96.8
1  female       2  0.921053                   92.1
2  female       3  0.500000                   50.0
3    male       1  0.368852                   36.9
4    male       2  0.157407                   15.7
5    male       3  0.135447                   13.5


Ryhmitellään luokan mukaan ja tutkitaan, että vaikuttiko hinta selviytymiseen

In [18]:
fare_analysis = titanic.groupby(["pclass", "survived"])["fare"].agg(["mean", "median", "count"]).reset_index()

print("\nLipun hinnan yhteys selviytymiseen:\n")
print(fare_analysis)


Lipun hinnan yhteys selviytymiseen:

   pclass  survived       mean   median  count
0       1         0  64.684007  44.7500     80
1       1         1  95.608029  77.9583    136
2       2         0  19.412328  13.0000     97
3       2         1  22.055700  21.0000     87
4       3         0  13.669364   8.0500    372
5       3         1  13.694887   8.5167    119
